Document: ivoxely
Title: Debian ivoxely Manual
Author: <insert document author here>
Abstract: This manual describes what ivoxely is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ivoxely/ivoxely.sgml.gz

Format: postscript
Files: /usr/share/doc/ivoxely/ivoxely.ps.gz

Format: text
Files: /usr/share/doc/ivoxely/ivoxely.text.gz

Format: HTML
Index: /usr/share/doc/ivoxely/html/index.html
Files: /usr/share/doc/ivoxely/html/*.html
